name: Manually pass
on:
  workflow_dispatch:
    inputs:
      name: Manual Reason?
        discription: 'Why skip?'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
      - name: Doing nothing
        run: exit 0
