name: Manually pass
on:
  workflow_dispatch:
    inputs:
      name:
        discription: 'Why'
        required: true
        default: 'because'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: exit 0
